/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stateminimizer.withimplicationtable.Gui;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.*;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import stateminimizer.withimplicationtable.Model.*;


/**
 *
 * @author Adham Hamada
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private TransitionInputPanel transitionController;
    private ImplicationTablePanel drawPanel;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        transitionController = new TransitionInputPanel(
            transitionTable,
            transitionScrollPane,
            statusLabel
    );

    drawPanel = (ImplicationTablePanel) implicationDrawPanel;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setupPanel = new javax.swing.JPanel();
        statesLabel = new javax.swing.JLabel();
        statesSpinner = new javax.swing.JSpinner();
        inputsLabel = new javax.swing.JLabel();
        inputsSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        stateNamesField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buildTableButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        transitionLabel = new javax.swing.JLabel();
        transitionScrollPane = new javax.swing.JScrollPane();
        transitionTable = new javax.swing.JTable();
        minimizeButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        mainSplitPane = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        zoomInButton = new javax.swing.JButton();
        zoomOutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cellSizeSlider = new javax.swing.JSlider();
        tableScrollPane = new javax.swing.JScrollPane();
        implicationDrawPanel = new stateminimizer.withimplicationtable.Gui.ImplicationTablePanel();
        resultsTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        stepLogArea = new javax.swing.JTextArea();
        resultsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        minimizedFsmTable = new javax.swing.JTable();
        classesPanel = new javax.swing.JPanel();
        statusBar = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("State Minimizer — Implication Table Method");
        setMinimumSize(new java.awt.Dimension(1100, 700));

        setupPanel.setBackground(new java.awt.Color(204, 204, 204));
        setupPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("FSM Input"));
        setupPanel.setForeground(new java.awt.Color(0, 0, 0));
        setupPanel.setPreferredSize(new java.awt.Dimension(280, 650));

        statesLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        statesLabel.setForeground(new java.awt.Color(0, 0, 0));
        statesLabel.setText("Number of States:");
        setupPanel.add(statesLabel);

        statesSpinner.setModel(new javax.swing.SpinnerNumberModel(3, 2, 20, 1));
        statesSpinner.setMinimumSize(new java.awt.Dimension(80, 30));
        statesSpinner.setPreferredSize(new java.awt.Dimension(80, 30));
        setupPanel.add(statesSpinner);

        inputsLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inputsLabel.setForeground(new java.awt.Color(0, 0, 0));
        inputsLabel.setText("Number of Inputs:");
        setupPanel.add(inputsLabel);

        inputsSpinner.setModel(new javax.swing.SpinnerNumberModel(2, 1, 8, 1));
        inputsSpinner.setMinimumSize(new java.awt.Dimension(80, 30));
        setupPanel.add(inputsSpinner);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("State Names (optional):");
        setupPanel.add(jLabel1);

        stateNamesField.setColumns(18);
        stateNamesField.setToolTipText("Leave blank for S0,S1... or type: A,B,C,D");
        stateNamesField.setPreferredSize(new java.awt.Dimension(220, 28));
        stateNamesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateNamesFieldActionPerformed(evt);
            }
        });
        setupPanel.add(stateNamesField);

        jLabel4.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(136, 136, 136));
        jLabel4.setText("  e.g. A,B,C  or  q0,q1,q2");
        setupPanel.add(jLabel4);

        buildTableButton.setBackground(new java.awt.Color(74, 144, 217));
        buildTableButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buildTableButton.setForeground(new java.awt.Color(255, 255, 255));
        buildTableButton.setText("Build Transition Table");
        buildTableButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buildTableButton.setPreferredSize(new java.awt.Dimension(220, 35));
        buildTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildTableButtonActionPerformed(evt);
            }
        });
        setupPanel.add(buildTableButton);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setPreferredSize(new java.awt.Dimension(240, 10));
        setupPanel.add(jSeparator1);

        transitionLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        transitionLabel.setForeground(new java.awt.Color(0, 0, 0));
        transitionLabel.setText("Transition Table");
        setupPanel.add(transitionLabel);

        transitionScrollPane.setPreferredSize(new java.awt.Dimension(250, 300));

        transitionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        transitionTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        transitionTable.setFillsViewportHeight(true);
        transitionTable.setGridColor(new java.awt.Color(204, 204, 204));
        transitionTable.setRowHeight(28);
        transitionTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        transitionScrollPane.setViewportView(transitionTable);

        setupPanel.add(transitionScrollPane);

        minimizeButton.setBackground(new java.awt.Color(39, 174, 96));
        minimizeButton.setForeground(new java.awt.Color(255, 255, 255));
        minimizeButton.setText("▶  Minimize FSM");
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.setPreferredSize(new java.awt.Dimension(220, 40));
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });
        setupPanel.add(minimizeButton);

        resetButton.setBackground(new java.awt.Color(231, 76, 60));
        resetButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetButton.setPreferredSize(new java.awt.Dimension(220, 35));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        setupPanel.add(resetButton);

        getContentPane().add(setupPanel, java.awt.BorderLayout.WEST);

        mainSplitPane.setDividerLocation(420);
        mainSplitPane.setDividerSize(8);
        mainSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        mainSplitPane.setResizeWeight(0.6);
        mainSplitPane.setOneTouchExpandable(true);

        topPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Implication Table"));
        topPanel.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("Zoom in");

        zoomInButton.setText("Zoom in");
        zoomInButton.setFocusable(false);
        zoomInButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomInButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomInButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(zoomInButton);

        zoomOutButton.setText("Zoom out");
        zoomOutButton.setToolTipText("Zoom out");
        zoomOutButton.setFocusable(false);
        zoomOutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomOutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomOutButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(zoomOutButton);

        jLabel2.setText("  Cell Size:");
        jToolBar1.add(jLabel2);

        cellSizeSlider.setMinimum(40);
        cellSizeSlider.setValue(60);
        cellSizeSlider.setPreferredSize(new java.awt.Dimension(120, 30));
        cellSizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cellSizeSliderStateChanged(evt);
            }
        });
        jToolBar1.add(cellSizeSlider);

        topPanel.add(jToolBar1, java.awt.BorderLayout.NORTH);

        implicationDrawPanel.setBackground(new java.awt.Color(255, 255, 255));
        implicationDrawPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout implicationDrawPanelLayout = new javax.swing.GroupLayout(implicationDrawPanel);
        implicationDrawPanel.setLayout(implicationDrawPanelLayout);
        implicationDrawPanelLayout.setHorizontalGroup(
            implicationDrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        implicationDrawPanelLayout.setVerticalGroup(
            implicationDrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        tableScrollPane.setViewportView(implicationDrawPanel);

        topPanel.add(tableScrollPane, java.awt.BorderLayout.CENTER);

        mainSplitPane.setTopComponent(topPanel);

        resultsTabbedPane.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        stepLogArea.setEditable(false);
        stepLogArea.setColumns(20);
        stepLogArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        stepLogArea.setForeground(new java.awt.Color(0, 0, 255));
        stepLogArea.setLineWrap(true);
        stepLogArea.setRows(5);
        stepLogArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(stepLogArea);

        resultsTabbedPane.addTab("Step Log", jScrollPane1);

        resultsPanel.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Equivalence Classes & Minimized FSM");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        resultsPanel.add(jLabel3, java.awt.BorderLayout.NORTH);

        minimizedFsmTable.setBackground(new java.awt.Color(250, 255, 244));
        minimizedFsmTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        minimizedFsmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        minimizedFsmTable.setGridColor(new java.awt.Color(170, 170, 170));
        minimizedFsmTable.setRowHeight(30);
        jScrollPane2.setViewportView(minimizedFsmTable);

        resultsPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        classesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Equivalent State Groups"));
        classesPanel.setPreferredSize(new java.awt.Dimension(600, 80));
        resultsPanel.add(classesPanel, java.awt.BorderLayout.SOUTH);

        resultsTabbedPane.addTab("Results", resultsPanel);

        mainSplitPane.setBottomComponent(resultsTabbedPane);

        getContentPane().add(mainSplitPane, java.awt.BorderLayout.CENTER);

        statusBar.setBackground(new java.awt.Color(44, 62, 80));
        statusBar.setPreferredSize(new java.awt.Dimension(1100, 30));
        statusBar.setLayout(new java.awt.BorderLayout());

        statusLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setText("  Ready. Enter your FSM above and click 'Build Table'.");
        statusBar.add(statusLabel, java.awt.BorderLayout.WEST);

        infoLabel.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(170, 170, 170));
        infoLabel.setText("States: —  |  Inputs: —  ");
        statusBar.add(infoLabel, java.awt.BorderLayout.EAST);

        getContentPane().add(statusBar, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buildTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildTableButtonActionPerformed

    int states = (int) statesSpinner.getValue();
    int inputs = (int) inputsSpinner.getValue();
    String customNames = stateNamesField.getText();
    transitionController.buildTable(states, inputs, customNames);
    infoLabel.setText("States: " + states + "  |  Inputs: " + inputs + "  ");
    }//GEN-LAST:event_buildTableButtonActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
    // 1. Validate and build the state machine from the table
    StateMachine machine = transitionController.buildAndValidate();
    if (machine == null) return;  // validation failed

    // 2. Run the implication table algorithm
    ImplicationTable impTable = new ImplicationTable(machine);
    impTable.minimize();

    // 3. Send data to the custom drawing panel (top panel)
    drawPanel.loadData(impTable, machine.getStates());

    // 4. Fill the step-by-step log text area
    stepLogArea.setText("");
    for (String line : impTable.getStepLog()) {
        stepLogArea.append(line + "\n");
    }
    stepLogArea.setCaretPosition(0); // scroll to top

    // 5. Get equivalence classes from the algorithm
    List<Set<String>> classes = impTable.getEquivalenceClasses();

    // 6. Show colored badges in classesPanel
    showEquivalenceClasses(classes);

    // 7. Build the minimized FSM table in the Results tab
    buildMinimizedFsmTable(machine, classes,
            transitionController.getInputSymbols());

    // 8. Switch to the Results tab so user sees output
    resultsTabbedPane.setSelectedIndex(1); // 0=Log, 1=Results

    statusLabel.setText("  ✅ Done! Original: "
            + machine.getNumStates() + " states → Minimized: "
            + classes.size() + " states.");


    }//GEN-LAST:event_minimizeButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
    transitionController.reset();
    drawPanel.clear();
    stepLogArea.setText("");
    classesPanel.removeAll();
    classesPanel.revalidate();
    classesPanel.repaint();
    infoLabel.setText("States: —  |  Inputs: —  ");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void zoomOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomOutButtonActionPerformed
    int current = cellSizeSlider.getValue();
    int next    = Math.max(current - 10, cellSizeSlider.getMinimum());
    cellSizeSlider.setValue(next);
    }//GEN-LAST:event_zoomOutButtonActionPerformed

    private void zoomInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomInButtonActionPerformed
    int current = cellSizeSlider.getValue();
    int next    = Math.min(current + 10, cellSizeSlider.getMaximum());
    cellSizeSlider.setValue(next);
    }//GEN-LAST:event_zoomInButtonActionPerformed

    private void cellSizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cellSizeSliderStateChanged
        if (drawPanel != null) {
        int newSize = cellSizeSlider.getValue();
        drawPanel.setCellSize(newSize);
        int percent = (int)(((newSize - 40) / 80.0) * 100);
        statusLabel.setText("  Zoom: " + percent + "%  —  Cell size: " + newSize + "px");
        }
    }//GEN-LAST:event_cellSizeSliderStateChanged

    private void stateNamesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateNamesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateNamesFieldActionPerformed
   
    private void showEquivalenceClasses(List<Set<String>> classes) {
    classesPanel.removeAll();

    Color[] palette = {
        new Color(52,152,219), new Color(155,89,182),
        new Color(26,188,156), new Color(230,126,34),
        new Color(231,76,60),  new Color(149,165,166)
    };

    int colorIdx = 0;
    for (Set<String> group : classes) {
        // Build label text like "{ S0, S2 }"
        String text = "{ " + String.join(", ", group) + " }";
        JLabel badge = new JLabel(text);
        badge.setOpaque(true);
        badge.setBackground(palette[colorIdx % palette.length]);
        badge.setForeground(Color.WHITE);
        badge.setFont(new Font("Arial", Font.BOLD, 13));
        badge.setBorder(BorderFactory.createEmptyBorder(6, 12, 6, 12));
        classesPanel.add(badge);
        classesPanel.add(Box.createHorizontalStrut(8)); // spacing
        colorIdx++;
    }

    classesPanel.revalidate();
    classesPanel.repaint();
    }
    
    private void buildMinimizedFsmTable(StateMachine originalMachine,
                                    List<Set<String>> classes,
                                    String[] inputSymbols) {

    int numInputs = originalMachine.getNumInputs();

    // ── Step A: Build a map from original state name → representative name
    // The representative is the first state alphabetically in each group
    Map<String, String> representativeOf = new HashMap<>();
    List<String> representativeNames = new ArrayList<>();

    for (Set<String> group : classes) {
        // Use the first element as the representative
        // (LinkedHashSet preserves insertion order from the algorithm)
        String rep = group.iterator().next();
        representativeNames.add(rep);
        for (String member : group) {
            representativeOf.put(member, rep);
        }
    }

    // ── Step B: Build column headers
    // Layout: | State | Next(x=0) | Out(x=0) | Next(x=1) | Out(x=1) | ...
    String[] cols = new String[1 + numInputs * 2];
    cols[0] = "State";
    for (int i = 0; i < numInputs; i++) {
        cols[1 + i * 2]     = "Next (" + inputSymbols[i] + ")";
        cols[1 + i * 2 + 1] = "Out  (" + inputSymbols[i] + ")";
    }

    // ── Step C: Build one row per equivalence class
    Object[][] data = new Object[classes.size()][cols.length];

    for (int r = 0; r < representativeNames.size(); r++) {
        String repName = representativeNames.get(r);
        data[r][0] = repName;   // State column

        // Find this representative in the original machine
        State originalState = originalMachine.getState(repName);

        // If for some reason it's not found, try any member of the group
        if (originalState == null) {
            Set<String> group = classes.get(r);
            for (String member : group) {
                originalState = originalMachine.getState(member);
                if (originalState != null) break;
            }
        }

        if (originalState == null) continue; // safety check

        for (int inp = 0; inp < numInputs; inp++) {
            // Get original next state
            String originalNext = originalState.getNextStates()[inp];
            // Map it to its representative in the minimized machine
            String minimizedNext = representativeOf.getOrDefault(
                    originalNext, originalNext);

            String output = originalState.getOutputs()[inp];

            data[r][1 + inp * 2]     = minimizedNext;
            data[r][1 + inp * 2 + 1] = output;
        }
    }

    // ── Step D: Create a non-editable table model
    DefaultTableModel model = new DefaultTableModel(data, cols) {
        @Override
        public boolean isCellEditable(int row, int col) {
            return false;  // results table is read-only
        }
    };

    minimizedFsmTable.setModel(model);

    // ── Step E: Style the minimized FSM table
    styleMinimizedTable(classes, representativeNames);
}
    
// ══════════════════════════════════════════════════════════════════
//  styleMinimizedTable() — makes the result table look clean
// ══════════════════════════════════════════════════════════════════

private void styleMinimizedTable(List<Set<String>> classes,
                                 List<String> repNames) {

    Color[] palette = {
        new Color(214, 234, 248),  // light blue
        new Color(232, 218, 239),  // light purple
        new Color(213, 245, 227),  // light green
        new Color(253, 235, 208),  // light orange
        new Color(250, 219, 216),  // light red
        new Color(210, 241, 234),  // light teal
        new Color(253, 243, 207),  // light yellow
        new Color(234, 237, 237)   // light grey
    };

    minimizedFsmTable.setRowHeight(32);
    minimizedFsmTable.setFont(new Font("Arial", Font.PLAIN, 13));
    minimizedFsmTable.setShowGrid(true);
    minimizedFsmTable.setGridColor(new Color(180, 180, 180));
    minimizedFsmTable.getTableHeader()
            .setFont(new Font("Arial", Font.BOLD, 12));
    minimizedFsmTable.getTableHeader()
            .setBackground(new Color(44, 62, 80));
    minimizedFsmTable.getTableHeader()
            .setForeground(Color.WHITE);
    minimizedFsmTable.getTableHeader()
            .setPreferredSize(new Dimension(0, 35));

    // Color each row by its equivalence class index
    minimizedFsmTable.setDefaultRenderer(Object.class,
        new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable t,
                    Object val, boolean sel, boolean focus,
                    int row, int col) {
                Component c = super.getTableCellRendererComponent(
                        t, val, sel, focus, row, col);
                if (!sel) {
                    // Row index corresponds to equivalence class index
                    c.setBackground(palette[row % palette.length]);
                    if (col == 0) {
                        ((JLabel)c).setFont(
                                new Font("Arial", Font.BOLD, 13));
                    }
                }
                ((JLabel) c).setHorizontalAlignment(JLabel.CENTER);
                return c;
            }
        });

    // Auto-size columns
    minimizedFsmTable.getColumnModel().getColumn(0)
            .setPreferredWidth(70);
    for (int i = 1; i < minimizedFsmTable.getColumnCount(); i++)
        minimizedFsmTable.getColumnModel().getColumn(i)
                .setPreferredWidth(100);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buildTableButton;
    private javax.swing.JSlider cellSizeSlider;
    private javax.swing.JPanel classesPanel;
    private javax.swing.JPanel implicationDrawPanel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel inputsLabel;
    private javax.swing.JSpinner inputsSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JTable minimizedFsmTable;
    private javax.swing.JButton resetButton;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JTabbedPane resultsTabbedPane;
    private javax.swing.JPanel setupPanel;
    private javax.swing.JTextField stateNamesField;
    private javax.swing.JLabel statesLabel;
    private javax.swing.JSpinner statesSpinner;
    private javax.swing.JPanel statusBar;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextArea stepLogArea;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel transitionLabel;
    private javax.swing.JScrollPane transitionScrollPane;
    private javax.swing.JTable transitionTable;
    private javax.swing.JButton zoomInButton;
    private javax.swing.JButton zoomOutButton;
    // End of variables declaration//GEN-END:variables
}
